const { createApp, ref, computed, onMounted } = Vue;
createApp({setup(){
 const impairment=ref(45),horizon=ref(5),result=ref(null),loading=ref(false),error=ref(''),mode=ref('patient'),week=ref(0),selected=ref('knee'),assessment=ref(null),assessmentSuite=ref(null),selectedProtocol=ref('gait'),observatory=ref(null),episode=ref(null),clinical=ref(null),population=ref(null),motion=ref(null),motionError=ref(''),uploadName=ref('');
 const fmt=(v,d=2)=>v===undefined||v===null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d); const latent=computed(()=>result.value?.latent_state||{}),bio=computed(()=>result.value?.biomechanics||{}),ev=computed(()=>result.value?.evidence||{}),policy=computed(()=>result.value?.apace_policy?.trajectory||[]);
 const capacity=computed(()=>week.value===0?(latent.value.motor_capacity??.5):(policy.value[week.value-1]?.capacity??.5));
 const fatigue=computed(()=>week.value===0?(latent.value.fatigue_burden??.4):(policy.value[week.value-1]?.fatigue??.4));
 const pain=computed(()=>week.value===0?(latent.value.pain_burden??.3):(policy.value[week.value-1]?.pain??.3));
 const asym=computed(()=>Math.min(.65,bio.value.bilateral_symmetry_index??.25));
 const lean=computed(()=>12+(1-capacity.value)*16); const leftKnee=computed(()=>180-(26+asym.value*24)); const rightKnee=computed(()=>180-(26-asym.value*10));
 const trajectory=(key)=>{let vals=[key==='capacity'?latent.value.motor_capacity:key==='fatigue'?latent.value.fatigue_burden:latent.value.pain_burden,...policy.value.map(x=>x[key])]; return vals.map((v,i)=>`${30+i*(500/Math.max(1,vals.length-1))},${180-135*Math.max(0,Math.min(1,v||0))}`).join(' ')};
 const branches=computed(()=>{let c=capacity.value,u=Number(result.value?.treatment_response_ml?.reference_std_gain||.01);return [
  {name:'BALANCE',gain:.10+(1-c)*.10,risk:.07+asym.value*.12,info:u*7,angle:-65},
  {name:'GAIT',gain:.13+(1-c)*.11,risk:.10+asym.value*.16,info:u*10,angle:-20},
  {name:'STRENGTH',gain:.09+(1-c)*.08,risk:.05+fatigue.value*.12,info:u*5,angle:25},
  {name:'INTEGRATED',gain:.12+(1-c)*.10,risk:.08+pain.value*.10,info:u*8,angle:65}]});
 async function run(){loading.value=true;error.value='';week.value=0;try{let r=await fetch(`/api/apace/demo?impairment=${impairment.value/100}&horizon=${horizon.value}&seed=42`),d=await r.json();if(!r.ok)throw Error(d.detail||'Computation failed');result.value=d}catch(e){error.value=e.message}finally{loading.value=false}}
 async function loadLab(kind){mode.value=kind; if(kind==='assessment'){assessmentSuite.value=await (await fetch(`/api/assessment/suite?impairment=${impairment.value/100}`)).json(); assessment.value=assessmentSuite.value[selectedProtocol.value]} if(kind==='observatory'){observatory.value=await (await fetch('/api/research/observatory?patients_per_phenotype=2&weeks=3')).json()} if(kind==='record'){clinical.value=await (await fetch(`/api/clinical/episode?impairment=${impairment.value/100}&phenotype=balanced&weeks=5&seed=42`)).json(); episode.value={weeks:clinical.value.weeks}} if(kind==='population'){population.value=await (await fetch('/api/adaptive/population-stress?patients_per_phenotype=3&weeks=4&seed=42')).json()}}
 function chooseProtocol(p){selectedProtocol.value=p;assessment.value=assessmentSuite.value?.[p]||null}
 const motionPts=(key)=>{let v=motion.value?.trace?.[key]||[];if(!v.length)return '';let lo=Math.min(...v),hi=Math.max(...v),span=Math.max(.001,hi-lo);return v.map((x,i)=>`${i*(300/Math.max(1,v.length-1))},${80-65*(x-lo)/span}`).join(' ')}
 async function analyzeFile(file){motionError.value=''; motion.value=null; uploadName.value=file?.name||''; if(!file)return; try{let text=await file.text(); let r=await fetch('/api/motion/landmarks',{method:'POST',headers:{'Content-Type':'text/csv'},body:text}); let d=await r.json(); if(!r.ok)throw Error(d.detail||'Motion analysis failed'); motion.value=d}catch(e){motionError.value=e.message}}
 async function loadBundled(){motionError.value=''; let r=await fetch('/api/motion/sample-analysis'); let d=await r.json(); motion.value=d; uploadName.value='observed_landmark_session.csv'}
 onMounted(()=>{run();const panel=document.createElement('aside');panel.style.cssText='position:fixed;right:22px;bottom:22px;width:min(420px,calc(100vw - 44px));z-index:30;background:#101c24;border:1px solid #35515d;border-radius:14px;padding:14px;box-shadow:0 20px 60px #000b;color:#eaf7fb;display:none';panel.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><b>REHAB//AI COPILOT</b><button id="rehabCopilotClose">×</button></div><div style="font-size:10px;color:#9db7c1;margin:6px 0 10px">Gemini optional · deterministic fallback · clinician review only</div><textarea id="rehabCopilotQuestion" rows="3" style="width:100%;background:#071018;color:#eaf7fb;border:1px solid #35515d;border-radius:8px;padding:8px" placeholder="What should I inspect before the next re-plan?"></textarea><div style="display:flex;gap:8px;margin-top:8px"><button id="rehabCopilotAsk">Ask Copilot</button><button id="rehabCopilotClear">Clear</button></div><pre id="rehabCopilotAnswer" style="white-space:pre-wrap;max-height:260px;overflow:auto;color:#d8edf3;font:12px/1.5 system-ui">Ask a question to generate a governed safety readout.</pre>';const toggle=document.createElement('button');toggle.textContent='AI COPILOT';toggle.style.cssText='position:fixed;right:22px;bottom:22px;z-index:29;padding:11px 14px;border-radius:999px;background:#86e1d2;color:#062019;border:0;font-weight:800;cursor:pointer';document.body.append(panel,toggle);toggle.onclick=()=>{panel.style.display=panel.style.display==='none'?'block':'none';toggle.style.display=panel.style.display==='none'?'block':'none'};panel.querySelector('#rehabCopilotClose').onclick=()=>{panel.style.display='none';toggle.style.display='block'};panel.querySelector('#rehabCopilotClear').onclick=()=>{panel.querySelector('#rehabCopilotQuestion').value='';panel.querySelector('#rehabCopilotAnswer').textContent='Ask a question to generate a governed safety readout.'};panel.querySelector('#rehabCopilotAsk').onclick=async()=>{const q=panel.querySelector('#rehabCopilotQuestion').value.trim();if(!q)return;const out=panel.querySelector('#rehabCopilotAnswer');out.textContent='Computing…';try{const r=await fetch('/api/copilot/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});const d=await r.json();if(!r.ok)throw Error(d.detail||d.error||'Copilot unavailable');out.textContent=d.answer+'\n\n['+d.provider+' / '+d.model+']'}catch(e){out.textContent='Copilot error: '+e.message}}});
 return{impairment,horizon,result,loading,error,mode,week,selected,fmt,latent,bio,ev,policy,capacity,fatigue,pain,asym,lean,leftKnee,rightKnee,trajectory,branches,run,assessment,assessmentSuite,selectedProtocol,chooseProtocol,observatory,episode,clinical,population,motion,motionError,uploadName,motionPts,loadLab,analyzeFile,loadBundled};
},template:`
<div class="lab" v-cloak>
 <header class="labbar"><div class="brand"><span class="pulse"></span><b>REHAB//AI</b><em>HUMAN MOTION & ADAPTIVE CONTROL LAB</em></div><div class="episode">{{result?.patient_id||'RECONSTRUCTING'}} <span>SYNTHETIC TWIN</span></div><div class="status"><a class="report-export" :href="'/api/clinical/report?impairment='+(impairment/100)+'&phenotype=balanced&weeks=5'">EXPORT EPISODE REPORT</a><i></i> COMPUTE ONLINE</div></header>
 <nav class="modebar platform-nav"><button :class="{active:mode==='patient'}" @click="loadLab('patient')">PATIENT BAY</button><button :class="{active:mode==='capture'}" @click="loadLab('capture')">MOTION CAPTURE</button><button :class="{active:mode==='assessment'}" @click="loadLab('assessment')">ASSESSMENT</button><button :class="{active:mode==='record'}" @click="loadLab('record')">PATIENT RECORD</button><button :class="{active:mode==='apace'}" @click="loadLab('apace')">APACE</button><button :class="{active:mode==='population'}" @click="loadLab('population')">POPULATION</button><button :class="{active:mode==='observatory'}" @click="loadLab('observatory')">OBSERVATORY</button><button :class="{active:mode==='theater'}" @click="loadLab('theater')">TWIN THEATER</button></nav>
 <div v-if="loading&&!result" class="boot"><div class="scanner"></div><b>RECONSTRUCTING HUMAN STATE</b><span>Synchronizing pose · IMU · biomechanics · probabilistic twin</span></div>
 <main v-else-if="result" class="stage">
  <section v-if="mode==='patient'" class="patient-bay">
   <div class="signal-rack"><div class="rack-title">LIVE EVIDENCE BUS</div><div class="signal"><span>IMU // 50Hz</span><svg viewBox="0 0 220 45"><path d="M0 25 L18 24 26 8 34 38 43 23 62 24 71 13 80 34 91 22 116 24 125 5 134 40 145 23 170 24 180 10 190 36 200 23 220 24"/></svg></div><div class="signal"><span>POSE // 25fps</span><div class="confidence"><i style="width:92%"></i></div><small>tracking confidence 0.92</small></div><div class="signal"><span>GAIT EVENT FUSION</span><div class="events"><b>HS</b><i></i><b>TO</b><i></i><b>HS</b><i></i><b>TO</b></div><small>pose + angular velocity consensus</small></div><div class="signal facts"><span>OBSERVED</span><strong>{{fmt(ev.gait_speed_mps,2)}} <small>m/s gait</small></strong><strong>{{fmt(ev.cadence_spm,0)}} <small>spm cadence</small></strong><strong>{{fmt(ev.knee_rom_deg,1)}}° <small>knee ROM</small></strong></div></div>
   <div class="human-bay">
    <div class="bay-label">DIGITAL PATIENT // SAGITTAL-FRONTAL FUSION</div><div class="patient-story"><small>PATIENT STATE</small><strong>{{Math.round(capacity*100)}}% FUNCTION</strong><span>{{bio.margin_of_stability_m < .02 ? 'Dynamic stability is limiting progression' : 'Motor capacity is improving within the current stability envelope'}}</span></div><div class="crosshair h"></div><div class="crosshair v"></div>
    <svg class="human" viewBox="0 0 520 680">
     <defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
     <g class="skeleton" :transform="'rotate('+(lean-18)+' 260 190)'">
      <circle cx="260" cy="92" r="38"/><line x1="260" y1="130" x2="260" y2="285"/><line x1="205" y1="165" x2="315" y2="165"/><line x1="205" y1="165" x2="168" y2="295"/><line x1="315" y1="165" x2="352" y2="295"/><line x1="260" y1="285" x2="210" y2="430"/><line x1="260" y1="285" x2="310" y2="430"/><line x1="210" y1="430" x2="192" y2="600"/><line x1="310" y1="430" x2="334" y2="600"/><line x1="170" y1="600" x2="215" y2="600"/><line x1="312" y1="600" x2="358" y2="600"/>
      <g class="joint" @click="selected='hip'"><circle cx="260" cy="285" r="13"/></g><g class="joint hot" @click="selected='knee'"><circle cx="210" cy="430" r="15"/><circle cx="310" cy="430" r="15"/></g><g class="joint" @click="selected='ankle'"><circle cx="192" cy="600" r="12"/><circle cx="334" cy="600" r="12"/></g>
     </g>
     <g class="com"><line :x1="250+(bio.com_position_m||0)*900" y1="260" :x2="250+(bio.extrapolated_com_m||0)*900" y2="590"/><circle :cx="250+(bio.com_position_m||0)*900" cy="260" r="8"/><circle :cx="250+(bio.extrapolated_com_m||0)*900" cy="590" r="8"/><text x="278" y="255">COM</text><text x="278" y="585">XCoM</text></g>
     <path class="bos" d="M160 615 L365 615 L390 640 L140 640 Z"/><line class="mos" :x1="250+(bio.extrapolated_com_m||0)*900" y1="630" x2="365" y2="630"/><text x="385" y="634">MoS {{fmt(bio.margin_of_stability_m,3)}}m</text>
    </svg>
    <div class="body-readout left"><label>LATENT MOTOR STATE</label><b>{{fmt(capacity,2)}}</b><span>UKF σ {{fmt(latent.std?.[0],3)}}</span></div><div class="body-readout right"><label>STABILITY RESERVE</label><b>{{fmt(latent.stability_reserve,2)}}</b><span>symmetry {{fmt(bio.bilateral_symmetry_index,2)}}</span></div>
    <div class="joint-panel"><span>{{selected.toUpperCase()}} ANALYSIS</span><b v-if="selected==='knee'">L {{fmt(leftKnee,0)}}° / R {{fmt(rightKnee,0)}}°</b><b v-else>tracking active</b><small>click a joint to interrogate</small></div>
   </div>
   <aside class="control-rig"><div class="rig-title">INTERVENTION RIG</div><label>IMPAIRMENT <b>{{impairment}}%</b></label><input type="range" min="10" max="90" step="5" v-model.number="impairment"><label>HORIZON <b>{{horizon}}W</b></label><div class="weeks"><button v-for="h in [3,4,5,6]" @click="horizon=h" :class="{on:horizon===h}">{{h}}</button></div><button class="compute" @click="run">RECONSTRUCT / SOLVE</button><div class="limits"><span>HUMAN PERFORMANCE ENVELOPE</span><div><i :style="{width:(capacity*100)+'%'}"></i></div><small>capacity {{fmt(capacity)}} · fatigue {{fmt(fatigue)}} · pain {{fmt(pain)}}</small></div><div class="next" v-if="policy.length"><span>APACE // NEXT CONTROL</span><strong>{{policy[0].action}}</strong><small>gain {{fmt(policy[0].expected_gain,3)}} · CVaR {{fmt(policy[0].cvar_loss,2)}}</small></div></aside>
   <div class="gait-strip"><div class="strip-label">GAIT CYCLE // MULTIMODAL EVENT FUSION</div><div class="leg"><b>LEFT</b><span class="stance" style="width:58%">STANCE</span><span class="swing">SWING</span></div><div class="leg offset"><b>RIGHT</b><span class="swing">SWING</span><span class="stance" style="width:56%">STANCE</span></div><div class="cursor" :style="{left:(10+week*14)+'%'}"></div><div class="eventmarks">HS <i></i> TO <i></i> HS <i></i> TO</div></div>
  </section>
  <section v-if="mode==='capture'" class="platform-workspace"><div class="hero-copy"><span>MOTION CAPTURE STUDIO</span><h1>Evidence enters here.</h1><p>Upload observed landmarks, inspect the reconstructed bilateral traces, and pass only ready signals downstream. Missing signals remain explicitly unavailable.</p></div><div class="capture-grid"><div class="dropzone functional"><input id="motion-file" type="file" accept=".csv,text/csv" @change="analyzeFile($event.target.files[0])"><label for="motion-file"><b>UPLOAD LANDMARK CSV</b><span>time_s · left/right heel Y · left/right knee angle</span></label><button class="sample-btn" @click="loadBundled">RUN BUNDLED ACCEPTANCE FIXTURE</button><div class="fixture-links"><a class="sample-link" href="/api/motion/sample">baseline fixture</a><a class="sample-link" href="/api/motion/sample-asymmetric">asymmetric fixture</a></div><i>{{uploadName || 'Observed input → computed gait features'}}</i><div v-if="motionError" class="motion-error">REJECTED // {{motionError}}</div></div><div class="pipeline-stack"><b>ANALYSIS RESULT</b><template v-if="motion"><div class="motion-metrics"><strong>{{motion.frames}}<small>frames</small></strong><strong>{{fmt(motion.knee_rom_deg,1)}}°<small>knee ROM</small></strong><strong>{{fmt(motion.bilateral_symmetry_index,3)}}<small>symmetry</small></strong><strong>{{fmt(motion.estimated_cadence_spm,0)}}<small>spm</small></strong></div><div class="motion-traces"><label>HEEL TRAJECTORIES</label><svg viewBox="0 0 300 90"><polyline class="trace-l" :points="motionPts('left_heel_y')"/><polyline class="trace-r" :points="motionPts('right_heel_y')"/></svg><label>KNEE ANGLES</label><svg viewBox="0 0 300 90"><polyline class="trace-l" :points="motionPts('left_knee_deg')"/><polyline class="trace-r" :points="motionPts('right_knee_deg')"/></svg></div><div class="readiness"><b>{{motion.readiness.state_estimation}}</b><span>Full protocol: {{motion.readiness.full_gait_assessment}}</span><small v-if="motion.readiness.missing_for_full_assessment.length">missing: {{motion.readiness.missing_for_full_assessment.join(', ')}}</small></div></template><template v-else><strong>01 Signal contract validation</strong><strong>02 Synchronization + QC</strong><strong>03 M-GEAR-ready gait evidence</strong><strong>04 Biomechanical reconstruction</strong></template></div></div></section>
  <section v-if="mode==='assessment'" class="platform-workspace"><div class="hero-copy"><span>ASSESSMENT LABORATORY</span><h1>{{assessment?.primary_limitation?.toUpperCase() || 'COMPUTING'}} is the primary limitation.</h1><p>{{assessment?.rationale}}</p></div><div class="protocol-switch"><button v-for="p in ['gait','balance','mobility','endurance']" :class="{on:selectedProtocol===p}" @click="chooseProtocol(p)">{{p}}</button></div><div class="assessment-suite"><div class="finding"><div><small>{{selectedProtocol.toUpperCase()}} SCORE</small><b>{{fmt(assessment?.score,2)}}</b><em>{{assessment?.severity}} impairment burden</em></div><ol><li v-for="x in assessment?.evidence">{{x}}</li></ol></div><div class="protocol-map"><div v-for="(f,name) in assessmentSuite" :class="{active:name===selectedProtocol}" @click="chooseProtocol(name)"><span>{{name}}</span><i><b :style="{width:(f.score*100)+'%'}"></b></i><strong>{{fmt(f.score,2)}}</strong></div></div></div></section>
  <section v-if="mode==='record'" class="platform-workspace"><div class="hero-copy"><span>LONGITUDINAL PATIENT RECORD</span><h1>The model must prove that it learned.</h1><p>Prediction is preserved before treatment, compared with observed response, and used to contract uncertainty before the next re-plan.</p></div><div class="learning-ledger" v-if="clinical"><div><small>UNCERTAINTY</small><b>{{fmt(clinical.learning.initial_uncertainty,3)}} → {{fmt(clinical.learning.final_uncertainty,3)}}</b><span>{{fmt(clinical.learning.uncertainty_reduction_pct,1)}}% contraction</span></div><div><small>PREDICTION ERROR</small><b>{{fmt(clinical.learning.mean_abs_prediction_error,4)}}</b><span>mean |observed − predicted|</span></div><div><small>REPLANS</small><b>{{clinical.learning.replans}}</b><span>closed-loop decisions</span></div><div><small>SAFETY</small><b>{{clinical.learning.envelope_violations}}</b><span>envelope violations</span></div></div><div class="timeline rich"><article v-for="w in clinical?.weeks"><small>WEEK {{w.week}}</small><b>{{w.action}}</b><div class="compare"><span>PRED {{fmt(w.predicted_gain,3)}}</span><span>OBS {{fmt(w.observed_gain,3)}}</span></div><span>capacity {{fmt(w.capacity)}} · fatigue {{fmt(w.fatigue)}} · pain {{fmt(w.pain)}}</span><span>load {{fmt(w.applied_load)}} / safe {{fmt(w.safe_limit)}}</span><em>belief σ {{fmt(w.parameter_std,3)}}</em></article></div><div class="evidence-ledger" v-if="clinical"><div v-for="e in clinical.evidence_ledger"><small>{{e.kind}}</small><b>{{e.label}}</b><span>{{e.value}}</span></div></div></section>
  <section v-if="mode==='population'" class="platform-workspace"><div class="hero-copy"><span>POPULATION RESEARCH LAB</span><h1>One algorithm. Heterogeneous humans.</h1><p>Stress APACE across response phenotypes and inspect actual synthetic-cohort gain, safety and uncertainty.</p></div><div class="population-summary" v-if="population"><div><small>COHORT</small><b>{{population.patients}}</b><span>synthetic episodes</span></div><div><small>PHENOTYPES</small><b>{{population.results.length}}</b><span>stress strata</span></div><div><small>SAFETY</small><b>{{fmt(Math.max(...population.results.map(x=>x.envelope_violation_rate))*100,1)}}%</b><span>worst violation rate</span></div></div><div class="phenotype-wall"><div v-for="p in population?.results || []"><b>{{p.phenotype.replaceAll('_',' ').toUpperCase()}}</b><span>gain {{fmt(p.mean_gain,3)}} · final {{fmt(p.mean_final_capacity,3)}}</span><strong>{{fmt(p.envelope_violation_rate*100,1)}}% violations</strong><i :style="{transform:'scale('+(0.65+p.mean_gain*1.5)+')'}"></i></div></div></section>
  <section v-if="mode==='observatory'" class="platform-workspace"><div class="hero-copy"><span>ALGORITHM OBSERVATORY</span><h1>Algorithms earn their place here.</h1><p>Benchmark safety, gain, uncertainty, runtime and phenotype robustness under reproducible synthetic stress.</p></div><div class="observatory"><div><small>PHENOTYPES</small><b>{{observatory?.metrics?.phenotypes}}</b></div><div><small>MEAN GAIN</small><b>{{fmt(observatory?.metrics?.mean_gain,3)}}</b></div><div><small>WORST PHENOTYPE</small><b>{{fmt(observatory?.metrics?.worst_phenotype_gain,3)}}</b></div><div><small>ENVELOPE VIOLATION</small><b>{{fmt(observatory?.metrics?.envelope_violation_rate*100,1)}}%</b></div><div class="observatory-rows" v-if="observatory?.cohort?.results"><div v-for="r in observatory.cohort.results"><b>{{r.phenotype.replaceAll('_',' ')}}</b><i><span :style="{width:Math.min(100,r.mean_gain*300)+'%'}"></span></i><strong>gain {{fmt(r.mean_gain,3)}}</strong><small>σ {{fmt(r.mean_final_uncertainty,3)}} · violations {{fmt(r.envelope_violation_rate*100,1)}}%</small></div></div></section>
  <section v-if="mode==='apace'" class="decision-chamber"><div class="chamber-title"><span>APACE // ADAPTIVE PATIENT-AWARE CONTROL & EXPLORATION</span><h1>Which intervention should happen <em>next?</em></h1><p>Recovery value and information value compete under a hard human-performance safety envelope.</p></div><div class="orbit"><div class="patient-core"><small>CURRENT BELIEF</small><b>{{fmt(capacity,2)}}</b><span>motor capacity</span><i :style="{transform:'scale('+Math.max(.4,latent.std?.[0]*12)+')'}"></i></div><div v-for="(b,i) in branches" class="branch" :class="{chosen:policy[0]?.action?.toUpperCase().includes(b.name.split(' ')[0])}" :style="{transform:'rotate('+b.angle+'deg) translateX(250px) rotate('+(-b.angle)+'deg)'}"><strong>{{b.name}}</strong><div><span>GAIN {{fmt(b.gain,2)}}</span><span>TAIL {{fmt(b.risk,2)}}</span><span>INFO {{fmt(b.info,2)}}</span></div></div></div><div class="equation">A(a) = <b>E[ΔFUNCTION]</b> + λₜ <b>IG(a)</b> − β <b>CVaRα</b> − η <b>BURDEN</b></div><div class="policy-sequence"><div v-for="(s,i) in policy"><small>W{{s.week}}</small><b>{{s.action}}</b><span>gain {{fmt(s.expected_gain,3)}}</span><i></i></div></div><div class="solver-stamp">{{result.apace_policy.status}}<small>{{result.apace_policy.expanded_nodes}} nodes expanded / {{result.apace_policy.pruned_unsafe}} unsafe pruned</small></div></section>
  <section v-if="mode==='theater'" class="twin-theater"><div class="theater-head"><span>TWIN THEATER</span><h1>Counterfactual recovery futures</h1><p>Scrub the horizon. Watch capacity, fatigue and pain evolve under the selected adaptive policy.</p></div><div class="future-space"><div class="now"><i></i><b>NOW</b></div><svg viewBox="0 0 600 220"><path class="future ghost" d="M20 110 C130 60 190 55 290 45 S460 28 580 22"/><path class="future selected" d="M20 110 C120 92 210 75 300 60 S470 44 580 40"/><path class="future risk" d="M20 110 C125 120 210 142 300 155 S455 178 580 190"/><circle v-for="i in horizon" :cx="20+i*(560/horizon)" :cy="110-i*12" r="5" class="node"/></svg><div class="future-label best">AGGRESSIVE // higher gain, lower headroom</div><div class="future-label ap">APACE // selected adaptive path</div><div class="future-label bad">OVERLOAD // envelope violation</div></div><div class="scrubber"><input type="range" min="0" :max="policy.length" v-model.number="week"><div><b>{{week===0?'CURRENT STATE':'WEEK '+week}}</b><span>capacity {{fmt(capacity)}} / fatigue {{fmt(fatigue)}} / pain {{fmt(pain)}}</span></div></div><div class="traces"><div><span>CAPACITY</span><svg viewBox="0 0 560 200"><polyline :points="trajectory('capacity')"/></svg></div><div><span>FATIGUE</span><svg viewBox="0 0 560 200"><polyline :points="trajectory('fatigue')"/></svg></div><div><span>PAIN</span><svg viewBox="0 0 560 200"><polyline :points="trajectory('pain')"/></svg></div></div></section>
 </main><div v-if="error" class="error">{{error}}</div>
</div>`}).mount('#app');
